<?php

/**
 * @file
 * Module functionality.
 */

/**
 * Implements hook_menu().
 */
function ding_custom_facets_menu() {
  $items = array();

  $items['admin/config/ding/facet-groups'] = array(
    'title' => 'Custom facet groups',
    'description' => 'Adding facet groups and terms.',
    'page callback' => array('ding_custom_facets_admin_page'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_custom_facets.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/ding/facet-groups/overview'] = array(
    'title' => 'Custom facet groups + terms',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/config/ding/facet-groups/add'] = array(
    'title' => 'Add new group',
    'description' => 'Create new group',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_custom_facets_add_item_page'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_custom_facets.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  $items['admin/config/ding/facet-groups/%group/view'] = array(
    'title' => 'View group',
    'load arguments' => array(4),
    'page callback' => 'ding_custom_facets_view_item_page',
    'page arguments' => array(4),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_custom_facets.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/ding/facet-groups/%group/edit'] = array(
    'title' => 'Edit group',
    'load arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_custom_facets_item_form', 4),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_custom_facets.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/ding/facet-groups/%group/delete'] = array(
    'title' => 'Edit group',
    'load arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_custom_facets_item_delete_form', 4),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_custom_facets.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/ding/facet-groups/%group/term/%/delete'] = array(
    'title' => 'Delete terms',
    'page callback' => 'ding_custom_facets_terms_delete_term',
    'page arguments' => array(4, 6),
    'access arguments' => array('administer site settings'),
    'file' => 'ding_custom_facets.admin.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function ding_custom_facets_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Requesting group object form database.
 */
function group_load($gid) {
  return db_query('SELECT * FROM {ding_custom_facets_groups} WHERE gid = :gid', array(':gid' => $gid))->fetchObject();
}

/**
 * Implements hook_theme().
 */
function ding_custom_facets_theme($existing, $type, $theme, $path) {
  return array(
    'ding_custom_facets_terms_form' => array(
      'render element' => 'form',
      'file' => 'ding_custom_facets.admin.inc',
    ),
  );
}


/**
 * Implements hook_form().
 */
function ding_custom_facets_render_form($form, &$form_state, $group, $terms) {
  $path = current_path();
  $request_uri = urldecode(request_uri());
  $qp = drupal_get_query_parameters();

  $form['#attributes'] = array(
    'data-form-type' => $group->type,
    'class' => array('ding-custom-facets-form'),
  );
  // Creating fieldset for a group.
  $form['facet_groups_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => $group->name,
  );

  foreach ($terms as $term) {
    $checked = FALSE;

    switch ($group->type) {
      case 'simple':
        $url = $path . ' ' . $term->term;

        $link = l($term->label, $url);

        if ($qp) {
          $link = l($term->label, $url, array('query' => array($qp)));
        }

        if (strpos($request_uri, $term->term) != FALSE) {
          // Check the selected option checkbox.
          $checked = TRUE;

          // Change link for unchecking operation.
          $param = str_replace($term->term, '', $path);
          $url = trim($param);
          $link = l($term->label, $url);

          if ($qp) {
            $link = l($term->label, $url, array('query' => array($qp)));
          }
        }
        break;

      case 'advanced':
        $url = 'search/ting/' . $term->term;
        $link = l($term->label, $url);
        if (strpos($request_uri, $term->term) != FALSE) {
          $checked = TRUE;
          $param = str_replace($term->term, '', $path);
          $url = trim($param);
          $link = l($term->label, $url);
        }
        break;
    }


    // Render checkbox field.
    $form['facet_groups_fieldset'][$term->id] = array(
      '#type' => 'checkbox',
      '#title' => $link,
      '#default_value' => $checked,
    );
  }

  return $form;
}
